"""rm genre unique cond

Revision ID: 0cc93da2df22
Revises: 16fbb8445d3f
Create Date: 2022-06-02 09:17:26.361166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc93da2df22'
down_revision = '16fbb8445d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('genres_name_key', 'genres', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('genres_name_key', 'genres', ['name'])
    # ### end Alembic commands ###
