"""m2m

Revision ID: ee52f8049007
Revises: 2cc9ce2046b4
Create Date: 2022-06-03 03:14:58.862839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee52f8049007'
down_revision = '2cc9ce2046b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistgenres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('venuegenres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.drop_constraint('artists_name_key', 'artists', type_='unique')
    op.drop_constraint('genres_venue_id_fkey', 'genres', type_='foreignkey')
    op.drop_constraint('genres_artist_id_fkey', 'genres', type_='foreignkey')
    op.drop_column('genres', 'venue_id')
    op.drop_column('genres', 'artist_id')
    op.drop_constraint('venues_name_key', 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venues_name_key', 'venues', ['name'])
    op.add_column('genres', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('genres', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('genres_artist_id_fkey', 'genres', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key('genres_venue_id_fkey', 'genres', 'venues', ['venue_id'], ['id'])
    op.create_unique_constraint('artists_name_key', 'artists', ['name'])
    op.drop_table('venuegenres')
    op.drop_table('artistgenres')
    # ### end Alembic commands ###
