"""add genre unique cons

Revision ID: fbc3e6e571b6
Revises: 0cc93da2df22
Create Date: 2022-06-02 09:49:12.610740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc3e6e571b6'
down_revision = '0cc93da2df22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genres', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    # ### end Alembic commands ###
